// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: next_fetch.sql

package database

import (
	"context"
)

const getNextFetched = `-- name: GetNextFetched :one
SELECT id, created_at, updated_at, name, url, user_id, last_fetched_at 
FROM feeds 
ORDER BY last_fetched_at NULLS first 
LIMIT 1
`

func (q *Queries) GetNextFetched(ctx context.Context) (Feed, error) {
	row := q.db.QueryRowContext(ctx, getNextFetched)
	var i Feed
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Name,
		&i.Url,
		&i.UserID,
		&i.LastFetchedAt,
	)
	return i, err
}
